---
- name: Prepare Docker on NVIDIA runtimes
  hosts: docker-cuda
  become: yes
  tasks:
    - name: Ensure NVIDIA docker runtime is configured correctly
      template:
        src: "docker-daemon.json.j2"
        dest: "/etc/docker/daemon.json"
      notify:
        - Restart Docker

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

